### ISSUE TITLE
Outdated package on PyPI

### ISSUE THREAD

**Issue by safl** [SamsungDS/Spex#30]
The package on PyPi is ``v0.0.1``, thus when following the documentation at https://samsungds.github.io/Spex/setup/manual.html#sec-setup-manual then the user ends up with a severely outdated version of ``spex``.

This should be fixed such that the latest version of ``spex`` is deployed to PyPI. Ideally, this is automated and triggered by e.g. pushes to version-tags.

**Comment by mbrsamsung** [comment]
There is an issue with the current auto deployment from github runners. I am looking into it

**Comment by mbrsamsung** [comment]
The pypi repository is now updated with the newest version of nvme-spex.
