### ISSUE TITLE
Versioning info?

### ISSUE THREAD

**Issue by safl** [SamsungDS/Spex#32]
I see two versions defined, one in the ``spex`` package:

* ``src/spex/__init__.py``

And one in the ``spexsrv`` package:

* ``src/spexsrv/__init__.py``

The ``pyproject.toml`` points to the version from the ``spex`` package. Is the version in ``spexsrv`` needed?

**Comment by mbrsamsung** [comment]
No it should be removed. Thanks for spotting this.

**Comment by mbrsamsung** [comment]
The pull request #40 should fix this
